Lesson7
ensane094/UI pull request #2
Opened 2021-12-07 18:44 UTC by ensane094

2021-12-12 09:32 UTC, efserg approved these changes

2021-12-12 09:32 UTC, efserg commented on src/main/java/com/example/mychat/Controller.java
> +        if(message.startsWith("/w")){
Зачем тут эта проверка?

2021-12-12 15:03 UTC, ensane094 commented on src/main/java/com/example/mychat/Controller.java
> +        if(message.startsWith("/w")){
ой, точно! Я видно что-то хотел там написать и забыл

2021-12-21 15:07 UTC, efserg requested changes

2021-12-21 15:07 UTC, efserg commented on src/main/java/server/ClientHandler.java
> +                        closeConnection();                      /*и казалось бы... Но если другой клиент не успеет авторизоваться
А клиент-то знает, что сервер его отключил? Думаю, клиент продолжает пытаться соединится с сервером по открытому сокету. Поэтому лучше послать на клиент какой-нибудь сигнал завершения, чтобы он корректно завершил работу. Например, на клиенте у нас есть команда `/end`, что-то в этом духе можно использовать на сервере. Т.е. можно здесь вместо прямого вызова closeConnection послать клиенту команду `/end`, клиент ее у себя обработает, и пошлет в ответ серверу `/end`, а ее мы уже обрабатывать умеем. Не уверен, что это решит проблему, но попробовать можно

2022-01-26 21:08 UTC, merged